### PR TITLE
chore: modify cico script to build pr-sanitizer

### PR DESCRIPTION
**Pull request by dipak-pawar**
This PR adds pr-sanitizer to build and deploy in openshift cluster

### CODE REVIEW

**Comment by MatousJobanek** [comment]
Waiting for https://github.com/openshiftio/saas-errortracking/pull/9 being merged

**Comment by jmelis** [comment]
https://github.com/openshiftio/saas-errortracking/pull/9 has been merged

**Comment by jmelis** [comment]
cc @MatousJobanek

**Comment by MatousJobanek** [comment]
Thanks a lot @jmelis

**Pull request merged**
