### PR TITLE
docs(#104): update test keeper images.

### LINKED ISSUE #104: Update test-keeper images
We have outdated images with wrong plugin name in the docs - we should update them with `alien-ike/test-keeper`

### PR DESCRIPTION
**Pull request by hemanik**
Replaces old test keeper images with wrong plugin name to the latest one.

#### Fixes #104

### CODE REVIEW

**Comment by hemanik** [comment]
Hi Matous, the problem is if I am trying to generate new images from my repo then the thumbnail for the author is mine instead of alien-ike. (as seen below). Hence, had to use the images from Bartosz's repo.
 
screenshot from 2018-05-31 16-11-13

**Comment by MatousJobanek** [comment]
[test]

**Comment by alien-ike** [comment]
Hey @dipak-pawar! It seems you tried to trigger `/run` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver or pull request creator for this command to take an effect.

**Pull request merged**
