### PR TITLE
fix(#135): removes unnecessary logging of GH API errors

### PR DESCRIPTION
**Pull request by MatousJobanek**
Fixes: #135

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @MatousJobanek for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/arquillian/ike-prow-plugins/da9fc5b0369eae9a4508b1063a98e861ad15fe0f/test-keeper.yaml).

**Comment by MatousJobanek** [comment]
Good point @bartoszmajsak, that is another "bug" that I missed :-).
The whole if should be:
```go
	if e == nil && response != nil && response.StatusCode >= 404 {
		return fmt.Errorf("server responded with %d status", response.StatusCode)
	}
```
The point is that we need to create a new error in case the retrieved is nil but status code is >= 404  - to make the retry function working. 
In addition, I guess that  we don't want to log every error, but only the aggregated one in [retry_client.go](
https://github.com/arquillian/ike-prow-plugins/blob/master/pkg/github/client/retry_client.go#L34-L38)
This takes me to the fact that the function name should be different. eg: `checkHTTPCode` or `handleHTTPError` or something like that

**Comment by MatousJobanek** [comment]
@hemanik @dipak-pawar could you please take a look at this PR when you find some time?

**Comment by alien-ike** [comment]
Hey @dipak-pawar! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Pull request merged**
