### PR TITLE
feat: add fabric8-build-service

### PR DESCRIPTION
**Pull request by chmouel**
Add fabric8-build-service, and since I am supposed to be providing a PR that has a length which is greater of a zero then here I am babbling. 

In short and yet very long description, I am adding the `fabric8-build-service` repository from the `fabric8-service` orgnasiation to the `plugins.yaml` so we can have great testing.

How wonderful is that? Is this description helped to better a better understanding of the title of this PR? One may never said!

Here is a bit of usefulness tho! The URL of the repo : 

https://github.com/fabric8-services/fabric8-build-service

although that's probably something you could have get from the yaml file change,

anyway, enjoy your day and thanks fo reading! 

Fixes: #234

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (pr-sanitizer)

Thank you @chmouel for this contribution!



This pull request doesn't comply with the conventions given by the `pr-sanitizer` plugin. The following items are necessary to fix:

#### PR description length
The PR description is too short - it is expected that the description should have more than 50 characters, but it has 0. More elaborated description is helpful for understanding the changes proposed in this PR. (Any issue links and it's keywords are excluded when the description length is being measured)

#### Issue link
The PR description is missing any issue link that would be used with any of the [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/). Having it in the PR description ensures that the issue is automatically closed when the PR is merged.

Your plugin configuration is stored in the [file](https://github.com/arquillian/ike-prow-plugins/blob/b3d3a3171b105d4dd56ed6e8632be9f09e62a093/.ike-prow/pr-sanitizer.yml).

**Comment by chmouel** [comment]
[test]

**Comment by dipak-pawar** [comment]
Thanks @chmouel. LGTM

**Comment by dipak-pawar** [comment]
[test]

**Comment by chmouel** [comment]
can we have a merge please?

**Comment by dipak-pawar** [comment]
@chmouel: We have updated new config map as per this pr change. Could you please verify it on your side?

**Comment by chmouel** [comment]
@dipak-pawar thanks dipak, it was working but doesn't seem active anymore, did the job recovered from the prodpreview outages?

**Pull request merged**
