### PR TITLE
fix(#160): wip plugin handles also synchronize PR action

### PR DESCRIPTION
**Pull request by MatousJobanek**
Fixes: #160

### CODE REVIEW

**Comment by alien-ike** [comment]
Hey @hemanik! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by dipak-pawar** [comment]
@MatousJobanek wouldn't it be good if we add test for this new synchronize action?

**Pull request merged**
