### PR TITLE
chore(#150): adds RHEL based dockerfile used in CICO master build

### PR DESCRIPTION
**Pull request by MatousJobanek**
* added RHEL based dockerfile that should be pushed to devshift only from ci.centos.org master build
* renamed `Dockerfile.prow` to `Dockerfile.deploy` to keep the convention naming used in other OSIO projects

Fixes: #150

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @MatousJobanek for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/arquillian/ike-prow-plugins/cda15dd1b608e653bfd0339d158ad63ad3473323/test-keeper.yaml).

**Comment by MatousJobanek** [comment]
I totally forgot to check the target - thanks a lot for pointing this out @jmelis and for the proposal

two execution of the script should pass without any problem:
* the docker image should be cleaned when the script stops
* even if it wasn't be cleaned up, the `prepare` function should pass twice without any problem

**Comment by MatousJobanek** [comment]
[test]

**Pull request merged**
