### PR TITLE
Use IMAGE_TAG to comply with saasherder

### PR DESCRIPTION
**Pull request by jmelis**

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jmelis for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/arquillian/ike-prow-plugins/b231a9c952e8a0530e16856b71de595c1d17f0da/test-keeper.yaml).

**Comment by jmelis** [comment]
@MatousJobanek I agree with your changes, thanks!

**Comment by MatousJobanek** [comment]
[test]

**Pull request merged**
